version: '3'
services:
  jinjer_mysql:
    image: mysql:5.7
    volumes:
      - ./jinjer_mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=jinjer_core
      - MYSQL_PASSWORD=none
      - MYSQL_ROOT_PASSWORD=none
    command: mysqld --sql_mode=""
    ports:
      - "8888:3306"
  keihi_jinjer_core:
    image: docker/php8.2:latest
    depends_on:
      - jinjer_mysql
      - keihi_jinjer_core_redis
    volumes:
      - ./keihi_jinjer_core:/app
    environment:
      - WEBROOT=/app
#    expose:
#      - "8080"
    ports:
      - "1100:8080"
  keihi_jinjer_core_redis:
    image: redis:6
    ports:
      - "6379:6379"
#  jinjer_core72:
#    image: hoanglong01/nginx-php:052021
#    depends_on:
#      - jinjer_mysql
#      - jinjer_core_redis72
#    volumes:
#      - /Users/tomo/Documents/keihi_jinjer_core72:/app
#    environment:
#      - WEBROOT=/app
#    expose:
#      - "8080"
#    ports:
#      - "1500:8080"
#  jinjer_core_redis72:
#    image: redis:6
#    ports:
#      - "6382:6379"
#  jinjer_sso:
#    image: jinjer-sso
#    depends_on:
#      - jinjer_core
#      - jinjer_sso_redis
#    build:
#      context: /home/bauhq/Documents/jinjer_hr_auth
#      dockerfile: Dockerfile
#      args:
#        APP_ENV: local
#    command: "app"
#    volumes:
#      - /home/bauhq/Documents/jinjer_hr_auth:/usr/src/app
#      - ./shared:/shared #for php-fpm.sock
#    expose:
#      - "80"
#  jinjer_sso_webserver:
#    image: jinjer-sso
#    depends_on:
#      - jinjer_core
#      - jinjer_sso_redis
#    build:
#      context: /home/bauhq/Documents/jinjer_hr_auth
#      dockerfile: Dockerfile
#      args:
#        APP_ENV: local
#    command: "webserver"
#    volumes:
#      - ./shared:/shared #for php-fpm.sock
#    expose:
#      - "80"
#    ports:
#      - "1000:80"
#  jinjer_sso_redis:
#    image: redis:6
#    ports:
#      - "6379:6379"
  keihi_jinjer_jinji:
    image: docker/php8.2:latest
    depends_on:
      - keihi_jinjer_core
#      - keihi_jinjer_jinji_redis
    volumes:
      - ./jinjer_jinji_sessions:/jinjer_jinji_sessions
      - ./keihi_jinjer_jinji:/app
    environment:
      - WEBROOT=/app
    expose:
      - "8080"
    ports:
      - "1200:8080"
  keihi_jinjer_jinji_redis:
    image: redis:6
    ports:
      - "6380:6379"
#  jinjer_jinji_redis_reader:
#    image: redis:6
#    ports:
#      - "6381:6379"
#  jinjer_jinji72:
#    image: hoanglong01/nginx-php:052021
#    depends_on:
#      - jinjer_core
#      - jinjer_jinji_redis
#    volumes:
#      - /Users/tomo/Documents/docker-server/jinjer_jinji_sessions:/jinjer_jinji_sessions
#      - /Users/tomo/Documents/keihi_jinjer_jinji72:/app
#    environment:
#      - WEBROOT=/app
#    expose:
#      - "8080"
#    ports:
#      - "1400:8080"
  jinjer_hr_jinji:
    image: hoanglong01/nginx-php:052021
    depends_on:
      - keihi_jinjer_core
#      - keihi_jinjer_jinji_redis
    volumes:
      - ./jinjer_jinji_sessions:/jinjer_jinji_sessions
      - ./jinjer_hr_jinji:/app
    environment:
      - WEBROOT=/app
    expose:
      - "8080"
    ports:
      - "1600:8080"
  keihi_jinjer_expense:
    image: docker/php8.2:latest
    depends_on:
      - keihi_jinjer_core
    volumes:
      - ./keihi_jinjer_expense:/app
    environment:
      - WEBROOT=/app
    expose:
      - "8080"
    ports:
      - "1300:8080"
  nginx:
    image: zeroormax/linux-nginx-php7.4
    depends_on:
      - keihi_jinjer_core
      - keihi_jinjer_jinji
      - keihi_jinjer_expense
      - jinjer_hr_jinji
    volumes:
      - ./docker/certificate.crt:/var/certificate.crt
      - ./docker/private.key:/var/private.key
      - ./docker/default.conf:/etc/nginx/conf.d/vhost.conf
    ports:
      - "80:80"
      - "443:443"
